## Important NumPy Concepts

In [1]:
import numpy as np  # Import NumPy library

In [2]:
# This is a list of integers
Int_list = [1,2,3,4,5]  # Indexing operation on the array
Int_list  # Additional operation

[1, 2, 3, 4, 5]

In [3]:
# Create an array of integers
x = np.array(Int_list)  # Create a NumPy array
x  # Additional operation

array([1, 2, 3, 4, 5])

In [4]:
# Check for the type of array
type(x)  # Additional operation

numpy.ndarray

In [5]:
# Shows how many dimensions the array has
x.ndim  # Additional operation

1

In [6]:
# Shows the shape (the arrangement)
x.shape  # Additional operation

(5,)

In [7]:
# This is a matrix
x = [1,2,3]  # Indexing operation on the array
y = [4,5,6]  # Indexing operation on the array
my_list = [y,x]  # nested list
my_matrix = np.array(my_list)  # creating the matrix
my_matrix   # show the matrix

array([[4, 5, 6],
       [1, 2, 3]])

In [8]:
# Show the dimensions
my_matrix.ndim  # Additional operation

2

In [9]:
# Show the shape (the arrangement)
my_matrix.shape  # Additional operation

(2, 3)

In [10]:
my_matrix  # Additional operation

array([[4, 5, 6],
       [1, 2, 3]])

In [11]:
# Transpose the matrix (change the rows to columns)
t_matrix = my_matrix.transpose()  # Variable assignment
t_matrix  # show the new matrix

array([[4, 1],
       [5, 2],
       [6, 3]])

In [12]:
# Array of even numbers between 0 and 10
Even_array = np.arange(0,11,2)  # Create an array with a range of values
Even_array   # show the even number array

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# Array of even floating numbers between 0 and 10
Even_array2 = np.arange(0,11,2,dtype='float')  # Create an array with a range of values
Even_array2   # show the even floating number array

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [14]:
# Arrays of linearly spaced points
A = np.linspace(0,5,5)   # 5 equal pionts between 0 & 5
A  # show Array A

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [15]:
B = np.linspace(51,100)  # 50 equal points between 51 & 100
B  # show Array B

array([ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,  61.,
        62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
        73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,
        84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,
        95.,  96.,  97.,  98.,  99., 100.])

In [16]:
# Create a vector of 3 elements with zeros()
np.zeros(3)    # A vector of 3 elements

array([0., 0., 0.])

In [17]:
# Create a matrix of 6 elements: 2 rows, 3 columns
np.zeros((2,3))  # Additional operation

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# Create a vector of 3 elements with ones()
np.ones(3)      # A vector of 3 elememnts

array([1., 1., 1.])

In [19]:
# Create a matrix of 6 elements with ones()
np.ones((2,3))   # A matrix of 6 elements: 2 rows, 3 columns

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Create a vector 2 random values
np.random.rand(2)   # A vector of 2 random values

array([0.73248508, 0.02988756])

In [21]:
# Create a matrix of 6 random values
np.random.rand(2,3)  # A matrix of 6 random values

array([[0.31290165, 0.74601029, 0.86564308],
       [0.21752575, 0.48615572, 0.96782446]])

In [22]:
# Create a random value between 1 and 5
np.random.randint(1,5)    # A random value between 1 and 5

3

In [23]:
# Create a vector of 6 random values between 1 and 100
np.random.randint(1,100,6)  # Additional operation

array([54, 12, 71, 39, 98,  8])

In [24]:
# Create a matrix of 6 random values between 1 and 100
np.random.randint(1,100,(2,3))  # Additional operation

array([[43, 91, 82],
       [20, 31, 18]])

In [25]:
# Create a dice roll game with randinit()
# Define the function
def roll_dice():  # Additional operation
    #This function displays a dice roll value when called
    dice1 = np.random.randint(1,7)  # This allows 6 to be inclusive
    dice2 = np.random.randint(1,7)    # Variable assignment
    
    # Display condition
    if dice1 == dice2:  # Variable assignment
        print('Roll: ', dice1, '&', dice2,'\ndoubles!')  # Print the result
    if dice1 == 1:  # Variable assignment
        print('snake eyes')  # Print the result
    else:  # Additional operation
        print('Roll: ', dice1, '&', dice2)  # Print the result

In [26]:
# Call the function
roll_dice()  # Additional operation

Roll:  4 & 6


In [27]:
# Create 1d array
x = np.array([1,2,3])  # Create a NumPy array
x  # Additional operation

array([1, 2, 3])

In [28]:
# Create 2d array
y = np.array([(1,2,3),(4,5,6)])  # Create a NumPy array
y  # Additional operation

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Create range array
z = np.arange(1,10,2)  # Create an array with a range of values
z  # Additional operation

array([1, 3, 5, 7, 9])

In [30]:
# Add evenly spaced values btw interval to array of length
l = np.linspace(0,2,9)  # Variable assignment
l  # Additional operation

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
# Create an array filled with zeros
a = np.zeros((1,2))  # Variable assignment
a  # Additional operation

array([[0., 0.]])

In [32]:
# Create an array filled with ones
b = np.ones((1,2))  # Variable assignment
b  # Additional operation

array([[1., 1.]])

In [33]:
# Create random array
c = np.random.random((5,5))  # Variable assignment
c  # Additional operation

array([[0.9569499 , 0.53481655, 0.30591274, 0.05430286, 0.87917053],
       [0.16257284, 0.25145604, 0.25734291, 0.96784049, 0.59709853],
       [0.37672634, 0.3785197 , 0.12041916, 0.43400998, 0.49158785],
       [0.53081913, 0.43828688, 0.15685637, 0.85936307, 0.210186  ],
       [0.72737164, 0.75302948, 0.91889786, 0.12500115, 0.68619914]])

In [34]:
# Create an empty array
d = np.empty((2,2))  # Variable assignment
d  # Additional operation

array([[1.25, 2.5 ],
       [3.75, 5.  ]])

In [35]:
# Get Dimensios (Rows, Columns) of an array
y.shape  # Additional operation

(2, 3)

In [36]:
# Get length of array
len(x)  # Additional operation

3

In [37]:
# Get number of array dimensions
y.ndim  # Additional operation

2

In [38]:
# Get data type of array
x.dtype  # Additional operation

dtype('int32')

In [39]:
# Converts to data type
f = x.astype(float)  # Variable assignment
f  # Additional operation

array([1., 2., 3.])

In [40]:
# Get type of array
type(f)  # Additional operation

numpy.ndarray

In [41]:
# Import NumPy package
import numpy as np  # Import NumPy library

# Change the dimensions of an array with reshape()
freq = np.arange(10)   # Create a vector with 10 numbers
freq    # Show array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# Make freq 2 dimensional 5 rows, 2 columns
np.reshape(freq, (5,2))  # Reshape the array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
# Create a vector with 10 random numbers
values = np.random.rand(10)  # Variable assignment
values  # Additional operation

array([0.15672197, 0.19022125, 0.17166789, 0.75934033, 0.98330655,
       0.76634917, 0.12190456, 0.44142627, 0.47014191, 0.40448493])

In [44]:
# Make values 2 dimensional 2 rows, 5 columns
np.reshape(values, (2,5))  # Reshape the array

array([[0.15672197, 0.19022125, 0.17166789, 0.75934033, 0.98330655],
       [0.76634917, 0.12190456, 0.44142627, 0.47014191, 0.40448493]])

In [45]:
# Find the maximum value in the 'values' array
values.max()  # Additional operation

0.9833065481751366

In [46]:
# Find the index of the maximum value in the 'values' array
values.argmax()  # Additional operation

4

In [47]:
# Find the minimum value in the 'values' array
values.min()  # Additional operation

0.12190456196595323

In [48]:
# Find the index of the minimum value in the 'values' array
values.argmin()  # Additional operation

6

In [49]:
values  # Additional operation

array([0.15672197, 0.19022125, 0.17166789, 0.75934033, 0.98330655,
       0.76634917, 0.12190456, 0.44142627, 0.47014191, 0.40448493])

In [50]:
values[0]  # grabbing 1st item

0.15672196587618248

In [51]:
values[-1]  # grabbing last item

0.40448492834307714

In [52]:
values[1:3]  # grabbing 2nd & 3rd item

array([0.19022125, 0.17166789])

In [53]:
values[3:8]  # item 4 to 8

array([0.75934033, 0.98330655, 0.76634917, 0.12190456, 0.44142627])

In [54]:
# Create a list from 0 to 10
num_list = list(range(11))  # list from 0 to 10
num_list # show list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [55]:
list_slice = num_list[:4]  # first 4 items
list_slice     # show slice

[0, 1, 2, 3]

In [56]:
list_slice[:] = [5,7,9,3]   # Re-assignign elements
list_slice    # show updated values

[5, 7, 9, 3]

In [57]:
# Check for the original list
num_list     # show original list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [58]:
# Slice first 4 items in the list
list_slice = num_list[:4]      # first 4 items
list_slice      # show slice

[0, 1, 2, 3]

In [59]:
# Create an array from 0 to 10
num_array = np.arange(11)       # array from 0-10
num_array       # show array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
# Slice first 4 items in the array
array_slice = num_array[:4]     # first 4 items
array_slice      # show slice

array([0, 1, 2, 3])

In [61]:
# Re-assign elements
array_slice[:] = [5,7,9,3]   # Re-assign elements
array_slice     # show slice

array([5, 7, 9, 3])

In [62]:
# Check for the original array
num_array    # show original array

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
# Make a copy of the first 4 items of the original array
array_copy = num_array.copy()[:4]   # copies the first 4 items of the array 
array_copy   # show array

array([5, 7, 9, 3])

In [64]:
# Re-assign 10 to the copied array
array_copy[:] = 10     # re-assign 10 to the copied array
array_copy     # show array

array([10, 10, 10, 10])

In [65]:
# Check the original array
num_array   # show the original array

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# Create the matrix
matrix = np.array(([5,10,15],[20,25,30],[35,40,45]))  # Create a NumPy array
matrix     # display matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
# Grab the second row
matrix[1]  # Indexing operation on the array

array([20, 25, 30])

In [68]:
# Grab 35
matrix[2][0]  # Indexing operation on the array

35

In [69]:
# Grab first 2 rows
matrix[0:2]  # Indexing operation on the array

array([[ 5, 10, 15],
       [20, 25, 30]])

In [70]:
# Grab 45
matrix[2,2]  # Indexing operation on the array

45

In [71]:
# Grab the second column
column_slice = matrix[:,1:2]    # Assign the second column to a variable
column_slice  # Additional operation

array([[10],
       [25],
       [40]])

In [72]:
# Create an array of odd numbers between 0 and 20
odd_array = np.arange(0, 20, 2)   # an array of odd numbers between 0 and 20
odd_array       # show array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
# Extract elements above 11 into a new array
bool_array = odd_array > 11    # boolean conditional array
bool_array      # show array

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [74]:
# Get the values that we want by passing the bool_array into the original array
useful_array = odd_array[bool_array]   # the values we want
useful_array    # show array

array([12, 14, 16, 18])

In [75]:
# This code is more compact
compact_array = odd_array[odd_array > 11]    # one line 
compact_array    # show array

array([12, 14, 16, 18])

In [76]:
# Declare array one of 10 elements
array1 = np.arange(10).reshape(2, 5)   # create an array with 2 rows and 5 columns
array1   # show array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
# Declare array two of 10 elements
array2 = np.random.rand(10).reshape(2, 5)   # create an array with 2 rows and 5 columns
array2  # show array

array([[0.5314726 , 0.58824315, 0.62574145, 0.87396235, 0.3195084 ],
       [0.44765052, 0.03726213, 0.5466682 , 0.38458223, 0.93252164]])

In [78]:
# Addition
array_sum = array1 + array2  # Perform element-wise addition
array_sum    # show result array

array([[0.5314726 , 1.58824315, 2.62574145, 3.87396235, 4.3195084 ],
       [5.44765052, 6.03726213, 7.5466682 , 8.38458223, 9.93252164]])

In [79]:
# Subtraction
array_minus = array1 - array2  # Variable assignment
array_minus  # show result array

array([[-0.5314726 ,  0.41175685,  1.37425855,  2.12603765,  3.6804916 ],
       [ 4.55234948,  5.96273787,  6.4533318 ,  7.61541777,  8.06747836]])

In [80]:
# Multiplication
array_product = array1 * array2  # Variable assignment
array_product   # show result array

array([[0.        , 0.58824315, 1.2514829 , 2.62188704, 1.27803362],
       [2.23825259, 0.22357278, 3.82667737, 3.07665785, 8.39269475]])

In [81]:
# Division
array_divide = array1 / array2  # Variable assignment
array_divide   # show result array

array([[  0.        ,   1.69997729,   3.19620828,   3.43264216,
         12.51923251],
       [ 11.16942748, 161.02138868,  12.80484224,  20.80179309,
          9.65125057]])

In [82]:
# Create an array of values from 0 to 10
new_array = np.arange(0, 11)    # array of values from 0-10
new_array    # show array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
scalar = 100   # scalar value

In [84]:
# Create an array with a range from 100 - 110 using +
add_array = new_array + scalar    # add 100 to the every item in new_array
add_array    # show result array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [85]:
# Create an array of 100s using -
minus_array = add_array - new_array    # get 100s
minus_array    # show result array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [86]:
# Create an array using multiplication
multi_array = new_array * 100   # multiply by 100
multi_array   # show result array

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [87]:
# Create an array using division
err_array = new_array / new_array     # divide one array by another array. 
err_array    # show result array

C:\Users\dchen\AppData\Local\Temp\ipykernel_29832\3671682171.py:2: RuntimeWarning: invalid value encountered in divide
  err_array = new_array / new_array     # divide one array by another array.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [88]:
# Use univeral function for addition
u_add = np.add(new_array, scalar)   # add scalar value to the array
u_add   # show result array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [89]:
# Subtract one array from another array
u_sub = np.subtract(add_array, new_array)  # Variable assignment
u_sub   # show result array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [90]:
# Apply natural log on an array
u_log = np.log(new_array)  # Variable assignment
u_log   # show result array

C:\Users\dchen\AppData\Local\Temp\ipykernel_29832\2035590514.py:2: RuntimeWarning: divide by zero encountered in log
  u_log = np.log(new_array)  # Variable assignment


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [91]:
# Apply sine wave on an array
u_sine = np.sin(new_array)    # Variable assignment
u_sine    # show result array

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [92]:
# Find the maximum value using the .method
new_array.max()   # find maximum

10

In [93]:
# Find the maximum value using the max() method
np.max(new_array)  # find maximum

10

In [94]:
# Create a 2D array
np_array_2d = np.arange(0,6).reshape(2,3)  # Reshape the array
np_array_2d  # Additional operation

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
# Sum with axis = 0
np.sum(np_array_2d, axis=0)  # Variable assignment

array([3, 5, 7])

In [96]:
# Sum with axis = 1
np.sum(np_array_2d, axis=1)  # Variable assignment

array([ 3, 12])

In [97]:
freq = np.arange(10)  # Create an array with a range of values
freq  # Additional operation

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.reshape(freq, (5, 2))  # Reshape the array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [99]:
values = np.random.rand(10)  # Variable assignment
values  # Additional operation

array([0.86757343, 0.67811572, 0.4011323 , 0.73651793, 0.51365722,
       0.65484709, 0.94530883, 0.37395268, 0.74023335, 0.49687462])

In [100]:
np.reshape(values, (2, 5))  # Reshape the array

array([[0.86757343, 0.67811572, 0.4011323 , 0.73651793, 0.51365722],
       [0.65484709, 0.94530883, 0.37395268, 0.74023335, 0.49687462]])

In [101]:
np_array_2d = np.arange(0, 6).reshape((2,3))  # Reshape the array
np_array_2d  # Additional operation

array([[0, 1, 2],
       [3, 4, 5]])

In [102]:
values.max()  # Additional operation

0.9453088275515285

In [103]:
values.argmax()  # Additional operation

6

In [104]:
values.min()  # Additional operation

0.37395267559743317

In [105]:
values.argmin()  # Additional operation

7

In [106]:
values[0]  # Indexing operation on the array

0.8675734338051594

In [107]:
values[-1]  # Indexing operation on the array

0.496874620689572

In [108]:
values[1:3]  # Indexing operation on the array

array([0.67811572, 0.4011323 ])

In [109]:
values[3:8]  # Indexing operation on the array

array([0.73651793, 0.51365722, 0.65484709, 0.94530883, 0.37395268])

In [110]:
num_list = list(range(11))  # Variable assignment
num_list  # Additional operation

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [111]:
type(num_list)  # Additional operation

list

In [112]:
list_slice = num_list[:4]  # Indexing operation on the array
list_slice  # Additional operation

[0, 1, 2, 3]

In [113]:
list_slice[:] = [5, 7, 9, 3]  # Indexing operation on the array
list_slice  # Additional operation

[5, 7, 9, 3]

In [114]:
num_list  # Additional operation

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [115]:
num_array = np.arange(11)  # Create an array with a range of values

In [116]:
num_array  # Additional operation

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
type(num_array)  # Additional operation

numpy.ndarray

In [118]:
array_slice = num_array[:4]  # Indexing operation on the array
array_slice  # Additional operation

array([0, 1, 2, 3])

In [119]:
array_slice[:] = [5, 7, 9, 3]  # Indexing operation on the array
array_slice  # Additional operation

array([5, 7, 9, 3])

In [120]:
array_copy = num_array.copy()[:4]  # Create a copy of the array (not a view)
array_copy  # Create a copy of the array (not a view)

array([5, 7, 9, 3])

In [121]:
array_copy[:] = [1, 1, 1, 1]  # Create a copy of the array (not a view)
array_copy  # Create a copy of the array (not a view)

array([1, 1, 1, 1])

In [122]:
matrix = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))  # Create a NumPy array
matrix  # Additional operation

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [123]:
matrix[1]  # Indexing operation on the array

array([20, 25, 30])

In [124]:
matrix[2][0]  # Indexing operation on the array

35

In [125]:
matrix[:2]  # Indexing operation on the array

array([[ 5, 10, 15],
       [20, 25, 30]])

In [126]:
matrix[2][2]  # Indexing operation on the array

45

In [127]:
matrix[2, 2]  # Indexing operation on the array

45

In [128]:
matrix  # Additional operation

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [129]:
colum_slice = matrix[:, 1:3]  # Indexing operation on the array
colum_slice  # Additional operation

array([[10, 15],
       [25, 30],
       [40, 45]])

In [130]:
even_array = np.arange(0, 20, 2)  # Create an array with a range of values
even_array  # Additional operation

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [131]:
bool_array = even_array > 11  # Create a boolean mask
bool_array  # Additional operation

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [132]:
useful_array = even_array[bool_array]  # Indexing operation on the array
useful_array  # Additional operation

array([12, 14, 16, 18])

In [133]:
compact_array = even_array[even_array > 11]  # Create a boolean mask
compact_array  # Additional operation

array([12, 14, 16, 18])

In [134]:
array1 = np.arange(10).reshape(2, 5)  # Reshape the array
array1  # Additional operation

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [135]:
array2 = np.random.rand(10).reshape(2, 5)  # Reshape the array
array2  # Additional operation

array([[0.01076785, 0.65208188, 0.21308731, 0.30581511, 0.94344148],
       [0.35076832, 0.40653302, 0.11669713, 0.43856435, 0.19422649]])

In [136]:
#Addition
array_sum = array1 + array2  # Perform element-wise addition
array_sum  # Additional operation

array([[0.01076785, 1.65208188, 2.21308731, 3.30581511, 4.94344148],
       [5.35076832, 6.40653302, 7.11669713, 8.43856435, 9.19422649]])

In [137]:
#Substraction
array_minus = array1 - array2  # Variable assignment
array_minus  # Additional operation

array([[-0.01076785,  0.34791812,  1.78691269,  2.69418489,  3.05655852],
       [ 4.64923168,  5.59346698,  6.88330287,  7.56143565,  8.80577351]])

In [138]:
array_product = array1 * array2  # Variable assignment
array_product  # Additional operation

array([[0.        , 0.65208188, 0.42617462, 0.91744533, 3.77376593],
       [1.75384162, 2.43919809, 0.81687992, 3.50851482, 1.74803841]])

In [139]:
# Division
array_divide = array1 / array2  # Variable assignment
array_divide  # Additional operation

array([[ 0.        ,  1.53354975,  9.38582403,  9.80984888,  4.23979661],
       [14.25442281, 14.75894891, 59.98433685, 18.24133667, 46.33765461]])

In [140]:
new_array = np.arange(0, 11)  # Create an array with a range of values
new_array  # Additional operation

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
scalar = 100  # Variable assignment

In [142]:
add_array = new_array + scalar  # Perform element-wise addition
add_array  # Additional operation

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [143]:
minus_array = add_array - new_array  # Variable assignment
minus_array  # Additional operation

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [144]:
multi_array = new_array * scalar  # Variable assignment
multi_array  # Additional operation

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [145]:
err_array = new_array / new_array  # Variable assignment
err_array  # Additional operation

C:\Users\dchen\AppData\Local\Temp\ipykernel_29832\4266569895.py:1: RuntimeWarning: invalid value encountered in divide
  err_array = new_array / new_array  # Variable assignment


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [146]:
u_add = np.add(new_array, scalar)  # Variable assignment
u_add  # Additional operation

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [147]:
u_sub = np.subtract(add_array, new_array)  # Variable assignment
u_sub  # Additional operation

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [148]:
u_log = np.log(new_array)  # Variable assignment
u_log  # Additional operation

C:\Users\dchen\AppData\Local\Temp\ipykernel_29832\3030517451.py:1: RuntimeWarning: divide by zero encountered in log
  u_log = np.log(new_array)  # Variable assignment


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [149]:
u_sine = np.sin(new_array)  # Variable assignment
u_sine  # Additional operation

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [150]:
new_array.max()  # Additional operation

10

In [151]:
np.max(new_array)  # Additional operation

10

In [152]:
my_array = np.array(["Red", "Green", "Orange"])  # Create a NumPy array
my_array  # Additional operation

array(['Red', 'Green', 'Orange'], dtype='<U6')

In [153]:
extended = np.append(my_array, ["Yellow", "Pink"])  # Indexing operation on the array
extended  # Additional operation

array(['Red', 'Green', 'Orange', 'Yellow', 'Pink'], dtype='<U6')

In [154]:
my_array  # Additional operation

array(['Red', 'Green', 'Orange'], dtype='<U6')

In [155]:
zeros_array = np.zeros((3, 3))  # Variable assignment
zeros_array  # Additional operation

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [156]:
extended = np.append(zeros_array, [[1], [2], [3]], axis=1)  # Indexing operation on the array
extended  # Additional operation

array([[0., 0., 0., 1.],
       [0., 0., 0., 2.],
       [0., 0., 0., 3.]])

In [157]:
updated_array = np.delete(my_array, 1)  # Variable assignment
updated_array  # Additional operation

array(['Red', 'Orange'], dtype='<U6')

In [158]:
integer_random = np.random.randint(1, 11, size=(4,5))  # Variable assignment
integer_random  # Additional operation

array([[ 3,  4,  6,  1,  2],
       [ 9,  5,  8,  3,  3],
       [ 7,  4, 10,  4,  5],
       [ 3,  2,  3,  5,  3]])

In [159]:
updated_array = np.delete(integer_random, 1, axis=0)  # Variable assignment
updated_array  # Additional operation

array([[ 3,  4,  6,  1,  2],
       [ 7,  4, 10,  4,  5],
       [ 3,  2,  3,  5,  3]])

In [160]:
integer_random  # Additional operation

array([[ 3,  4,  6,  1,  2],
       [ 9,  5,  8,  3,  3],
       [ 7,  4, 10,  4,  5],
       [ 3,  2,  3,  5,  3]])

In [161]:
update_array = np.delete(integer_random, 1, axis=1)  # Variable assignment
update_array  # Additional operation

array([[ 3,  6,  1,  2],
       [ 9,  8,  3,  3],
       [ 7, 10,  4,  5],
       [ 3,  3,  5,  3]])

In [162]:
my_array = np.random.randint(1, 20, 10)  # Variable assignment
my_array  # Additional operation

array([18, 14,  8, 15,  7,  5, 14, 10, 13,  7])

In [163]:
sorted_array = np.sort(my_array)  # Variable assignment
sorted_array  # Additional operation

array([ 5,  7,  7,  8, 10, 13, 14, 14, 15, 18])

In [164]:
my_array = np.array(["Red", "Green", "Blue", "Yellow"])  # Create a NumPy array
my_array  # Additional operation

array(['Red', 'Green', 'Blue', 'Yellow'], dtype='<U6')

In [165]:
my_array = np.array([False, True, True, False, False, True, False, True])  # Create a NumPy array
my_array  # Additional operation

array([False,  True,  True, False, False,  True, False,  True])

In [166]:
my_array = np.random.randint(1, 20, size=(4, 6))  # Variable assignment
my_array  # Additional operation

array([[ 1, 16, 12, 10, 10, 11],
       [13,  6,  3,  8,  8, 10],
       [16, 17, 12, 12,  2, 18],
       [ 2, 10,  2,  5,  5,  7]])

In [167]:
reverse_sorted = np.flipud(sorted_array)  # Variable assignment
reverse_sorted  # Additional operation

array([18, 15, 14, 14, 13, 10,  8,  7,  7,  5])

In [168]:
two_d_array = np.random.randint(1, 20, size=(4,6))  # Variable assignment
two_d_array  # Additional operation

array([[ 3, 18,  6,  9,  4, 15],
       [ 7, 14, 10,  7,  9, 13],
       [ 4, 15,  4, 10,  7, 10],
       [ 3, 14,  8,  7,  3,  1]])

In [169]:
one_d_array = two_d_array.reshape(24)  # Reshape the array
one_d_array  # Additional operation

array([ 3, 18,  6,  9,  4, 15,  7, 14, 10,  7,  9, 13,  4, 15,  4, 10,  7,
       10,  3, 14,  8,  7,  3,  1])

In [170]:
two_d_array  # Additional operation

array([[ 3, 18,  6,  9,  4, 15],
       [ 7, 14, 10,  7,  9, 13],
       [ 4, 15,  4, 10,  7, 10],
       [ 3, 14,  8,  7,  3,  1]])

In [171]:
one_d_array = two_d_array.reshape(-1)  # Reshape the array
one_d_array  # Additional operation

array([ 3, 18,  6,  9,  4, 15,  7, 14, 10,  7,  9, 13,  4, 15,  4, 10,  7,
       10,  3, 14,  8,  7,  3,  1])

In [172]:
array1 = np.array([14, 25, 31])  # Create a NumPy array
array2 = np.array([10])  # Create a NumPy array
result = array1 + array2  # Perform element-wise addition
result  # Additional operation

array([24, 35, 41])

In [173]:
array1 = np.array([10, 12, 14, 16, 18, 20])  # Create a NumPy array
array1  # Additional operation

array([10, 12, 14, 16, 18, 20])

In [174]:
np.save(r"c:\temp\my_array.npy", array1)  # Additional operation

In [175]:
loaded_array = np.load(r"c:\temp\my_array.npy")  # Variable assignment
loaded_array  # Additional operation

array([10, 12, 14, 16, 18, 20])

In [176]:
np.savetxt(r"c:\temp\my_array.txt", array1)  # Additional operation

In [177]:
loaded_array = np.loadtxt(r"c:\temp\my_array.txt")  # Variable assignment
loaded_array  # Additional operation

array([10., 12., 14., 16., 18., 20.])

In [178]:
my_array = np.array([2,4,8,10, 12])  # Create a NumPy array
my_array  # Additional operation

array([ 2,  4,  8, 10, 12])

In [179]:
np.mean(my_array)  # Additional operation

7.2

In [180]:
my_array = np.random.randint(1, 20, size=(2,3))  # Variable assignment
my_array  # Additional operation

array([[ 9,  8,  4],
       [ 1, 18,  1]])

In [181]:
np.mean(my_array, axis=1)  # Variable assignment

array([7.        , 6.66666667])

In [182]:
np.mean(my_array, axis=0)  # Variable assignment

array([ 5. , 13. ,  2.5])

In [183]:
my_array = np.array([2,4,8, 10, 12])  # Create a NumPy array
my_array  # Additional operation

array([ 2,  4,  8, 10, 12])

In [184]:
np.median(my_array)  # Additional operation

8.0

In [185]:
my_array = np.random.randint(1,20, size=(3,4))  # Variable assignment
my_array  # Additional operation

array([[ 5, 12,  8, 19],
       [ 2, 15, 10, 19],
       [ 1,  9,  4,  7]])

In [186]:
np.amax(my_array, axis=1)  # Variable assignment

array([19, 19,  9])

In [187]:
np.amax(my_array, axis=0)  # Variable assignment

array([ 5, 15, 10, 19])

In [188]:
np.std(my_array)  # Additional operation

5.80409338312195

In [189]:
my_array = np.array([5,8,7, 5, 9, 3, 7, 7, 1, 1, 8, 4, 6, 9, 7, 3])  # Create a NumPy array
unique_items = np.unique(my_array)  # Variable assignment
unique_items  # Additional operation

array([1, 3, 4, 5, 6, 7, 8, 9])

In [190]:
unique_items, counts = np.unique(my_array, return_counts=True)  # Variable assignment
unique_items  # Additional operation

array([1, 3, 4, 5, 6, 7, 8, 9])

In [191]:
counts  # Additional operation

array([2, 2, 1, 2, 1, 4, 2, 2], dtype=int64)

In [192]:
frequencies = np.asarray((unique_items, counts))  # Variable assignment
frequencies  # Additional operation

array([[1, 3, 4, 5, 6, 7, 8, 9],
       [2, 2, 1, 2, 1, 4, 2, 2]], dtype=int64)

In [193]:
reversed_array = np.flipud(my_array)  # Variable assignment
reversed_array  # Additional operation

array([3, 7, 9, 6, 4, 8, 1, 1, 7, 7, 3, 9, 5, 7, 8, 5])

In [194]:
my_array = np.random.randint(1, 20, size=(3,4))  # Variable assignment
my_array  # Additional operation

array([[11,  3, 15,  4],
       [ 3, 12,  3,  1],
       [15,  4, 16, 15]])

In [195]:
reversed_array = np.fliplr(my_array)  # Variable assignment
reversed_array  # Additional operation

array([[ 4, 15,  3, 11],
       [ 1,  3, 12,  3],
       [15, 16,  4, 15]])

## Additional Important NumPy Concepts

In [196]:
# Broadcasting
import numpy as np  # Import NumPy library

A = np.array([1, 2, 3])  # Create a NumPy array
B = np.array([[1], [2], [3]])  # Create a NumPy array
result = A + B  # Broadcasting adds each row of B to A
print(result)  # Print the result

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [197]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])  # Create a NumPy array
mask = arr > 3  # Create a boolean mask
print(arr[mask])  # prints [4 5]

[4 5]


In [198]:
# Copy vs View
arr = np.array([1, 2, 3])  # Create a NumPy array
view = arr[1:]  # Indexing operation on the array
copy = arr[1:].copy()  # Create a copy of the array (not a view)
arr[1] = 100  # Indexing operation on the array
print(view)  # Affected
print(copy)  # Not affected

[100   3]
[2 3]


In [199]:
# Reshape with -1 (automatic calculation)
arr = np.arange(12)  # Create an array with a range of values
print(arr.reshape(3, -1))  # Reshape the array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
