<img src="../../predictioNN_Logo_JPG(72).jpg" width=200>

## Book Solutions
### Chapter 13: Modeling with Linear Regression

Last updated: May 9, 2023

---

2. True or False: You have a system of linear equations with more equations than unknowns. This system can be solved exactly.

Answer: False

A system with more equations than unknowns is an overdetermined system. It is not possible to solve this system exactly; regression is one method for solving such a system.

---

4. True or False: An intercept term adds flexibility to the linear regression model.

Answer: True

The additional parameter allows for greater flexibility in the model. For example, without an intercept term, the model output would be zero when all predictors are zero.

---

6. Explain how the parameters of a linear regression model can be estimated. The discussion should include the concept of critical points.

Answer: To estimate the parameters of a linear regression model, an expression for the sum of squared errors is established. Since the sum is a function of the parameters, it can be minimized by taking the derivative with respect to each parameter and finding the critical point. The critical point will indicate the parameter values such that the gradient is equal to zero.

---

8. Consider a simple linear regression model where the predictor is uncorrelated to the response variable. What do you expect will be the value of the slope parameter? 

Answer: If a predictor is uncorrelated to the response variable in a simple linear regression model, then we expect the slope parameter to have a value of zero.

---

10. True or False: You have a dataset with tens of thousands of potential predictors. The best practice is for the model to include all of the statistically significant predictors.

Answer: False

It is not enough to include predictors that are statistically significant. The variables should also make intuitive sense and they should avoid harmful consequences, such as introducing bias.

---

13. Explain how $R^2$ is related to correlation.

Answer: $R^2$ is the square of the correlation.

---

16. A residual plot shows a clear pattern. What does this mean?

Answer: A pattern in a residual plot suggests that a variable may be missing from the model.

---

18. Using the `sklearn` module, fit a linear regression model to this dataset: $\{(3,6),(3.5,9),(4,8)\}$. Show your code and print the intercept and slope coefficient estimates and the R-squared.

Answer: The code below will solve the task.

In [9]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score # R-squared

In [4]:
data = np.array([[3,6],[3.5,9],[4,8]])
data

array([[3. , 6. ],
       [3.5, 9. ],
       [4. , 8. ]])

In [10]:
X = data[:,0].reshape(-1, 1)
y = data[:,1].reshape(-1, 1)

reg = LinearRegression().fit(X,y)

In [11]:
reg.intercept_

array([0.66666667])

In [12]:
reg.coef_

array([[2.]])

In [16]:
# predicted y
y_pred = reg.predict(X)
y_pred

array([[6.66666667],
       [7.66666667],
       [8.66666667]])

In [15]:
print('R-squared:', r2_score(y, y_pred))

R-squared: 0.42857142857142794
